name: CI/CD Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No hay tests definidos"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      

      - name: Comprobar secretos
        run: |
          if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
            echo "ERROR: HEROKU_API_KEY está vacío"
            exit 1
          else
            echo "HEROKU_API_KEY está configurado"
          fi


      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}




